### ISSUE TITLE
48 test failures in org.osgi from I20220326-1800 using java 18

### ISSUE THREAD

**Issue by sravanlakkimsetti** [eclipse-equinox/equinox.framework#23]
Here are the test results

https://download.eclipse.org/eclipse/downloads/drops4/I20220326-1800/testresults/html/org.eclipse.osgi.tests_ep424I-unit-cen64-gtk3-java18_linux.gtk.x86_64_18.html

**Comment by sravanlakkimsetti** [comment]
@tjwatson Can you please take a look?

**Comment by tjwatson** [comment]
> @tjwatson Can you please take a look?

Yes, although I am confident these are test issues when the security manager is involved.  The tests are asking to run with the security manager, but the JVM will not allow it.

**Comment by HannesWell** [comment]
> Yes, although I am confident these are test issues when the security manager is involved. The tests are asking to run with the security manager, but the JVM will not allow it.

In this case, if you don't want to delete those tests and but just want to prevent them from running under Java-18 or later you could use [org.junit.Assume](https://junit.org/junit4/javadoc/4.12/org/junit/Assume.html).

**Comment by tjwatson** [comment]
> In this case, if you don't want to delete those tests and but just want to prevent them from running under Java-18 or later you could use [org.junit.Assume](https://junit.org/junit4/javadoc/4.12/org/junit/Assume.html).

I was considering that or I may want to conditionally run the tests of the system property `java.security.manager=allow` is set.  The latter is more complicated and may not be worth it if we really think they will follow through and complete remove the security manager in by the next LTS Java release (I still have my doubts there).

**Comment by HannesWell** [comment]
> > In this case, if you don't want to delete those tests and but just want to prevent them from running under Java-18 or later you could use [org.junit.Assume](https://junit.org/junit4/javadoc/4.12/org/junit/Assume.html).
> 
> I was considering that or I may want to conditionally run the tests if the system property `java.security.manager=allow` is set. The latter is more complicated and may not be worth it if we really think they will follow through and completely remove the security manager in by the next LTS Java release (I still have my doubts there).

AFAIK there is not fixed plan when to finally remove the Security-Manager, so it's hard to tell if it's worth more effort. Maybe the Java-Team also want's to have an LTS version where it is terminally deprecated and removes it after the next LTS, but that's just a personal guess.

**Comment by sravanlakkimsetti** [comment]
I made changes to propagate `-Djava.security.manager=allow` in tests and started recent tests again. Please check in the latest test results after 3 hours

**Comment by tjwatson** [comment]
We have one test failure remaining:
```
junit.framework.AssertionFailedError: Should be signed
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.assertTrue(Assert.java:22)
at junit.framework.TestCase.assertTrue(TestCase.java:192)
at org.eclipse.osgi.tests.security.SignedBundleTest.doTestBug378155(SignedBundleTest.java:889)
at org.eclipse.osgi.tests.security.SignedBundleTest.testBug378155(SignedBundleTest.java:872)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at junit.framework.TestCase.runTest(TestCase.java:177)
at junit.framework.TestCase.runBare(TestCase.java:142)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128)
at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
at org.eclipse.pde.internal.junit.runtime.RemotePluginTestRunner.main(RemotePluginTestRunner.java:74)
at org.eclipse.pde.internal.junit.runtime.CoreTestApplication.start(CoreTestApplication.java:28)
at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
at org.eclipse.core.launcher.Main.main(Main.java:44)
```

As @akurtakov pointed out in issue #25 this is because Java 18 has now dropped SHA1 support for signed JARs.  Because we now base our signed bundle support off the JarFile implementation of signed JARs we only support what the JVM does (which is a good thing).  I'm going to remove the testing of SHA1 signed jars here.
