### ISSUE TITLE
SecurityManagerTests.testBug254600 fails in Gerrit

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-equinox/equinox.framework#32]
https://ci.eclipse.org/equinox/job/rt.equinox.framework/job/PR-31/2/testReport/org.eclipse.osgi.tests.securityadmin/SecurityManagerTests/testBug254600/

```
org.osgi.framework.BundleException: Exception in security.b.Activator.start() of bundle security.b.
	at org.eclipse.osgi.tests.securityadmin.SecurityManagerTests.testBug254600(SecurityManagerTests.java:435)
Caused by: java.lang.SecurityException: Unable to create temporary file or directory
	at org.eclipse.osgi.tests.securityadmin.SecurityManagerTests.testBug254600(SecurityManagerTests.java:435)
```
Same test works fine locally.

**Comment by tjwatson** [comment]
I cannot make sense of the exception message there.  It seems we had a security exception thrown by the Activator.start method but that line number seems to have been lost.  I'm not sure why a temporary file is even being created during the activation here.  I may need to modify the test activator to get some more information.

**Comment by tjwatson** [comment]
I created surefire issue https://issues.apache.org/jira/browse/SUREFIRE-2069
